### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by meskobalazs** [kovzol/Java-Geometry-Expert#16]
There was this issue in the original project: https://github.com/yezheng1981/Java-Geometry-Expert/issues/2

The problem is two-fold. First, there is no direct information from the author. Second, a comment states there (copied from the Internet Archive)

> Java Geometry Expert is free under GNU General Public License (GPL).
> The user may download and distribute it freely.
> For commercial use, you must first contact the author.

These are contradictory statements. 

The best would be if @yezheng1981 would publicly state that the software is indeed firmly under GPL, preferably by adding a license file to the project (this or the original).

**Comment by kovzol** [comment]
I think the original authors, similarly to many other authors in the world, have no clear picture on what GPL means, that is, that commercial use is also possible. I will contact @yezheng1981 to clarifiy this.
